import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Instagraph',
  description: 'Terms and conditions for using the Instagraph platform.',
}

const LAST_UPDATED = 'February 26, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex flex-col">
      {/* Nav */}
      <nav className="border-b border-gray-800/60 bg-gray-950/90 backdrop-blur-sm sticky top-0 z-50">
        <div className="mx-auto max-w-7xl px-6 h-14 flex items-center justify-between">
          <Link href="/" className="text-white font-bold text-base tracking-tight">
            Instagraph
          </Link>
          <Link
            href="/"
            className="text-sm text-gray-400 hover:text-white transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 py-16 px-6">
        <div className="mx-auto max-w-2xl space-y-12">
          {/* Header */}
          <div className="space-y-3">
            <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
            <p className="text-gray-500 text-sm">Last updated: {LAST_UPDATED}</p>
            <p className="text-gray-400 text-sm leading-relaxed">
              These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Instagraph, operated by Instagraph
              (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing or using Instagraph, you agree to be bound
              by these Terms. If you do not agree, do not use the service.
            </p>
          </div>

          <Section title="1. The Service">
            <p className="text-gray-400 text-sm leading-relaxed">
              Instagraph provides a tool that uses AI to extract entities and relationships from crypto
              VC funding announcements and visualizes them as interactive knowledge graphs. The service
              is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis.
            </p>
          </Section>

          <Section title="2. Eligibility">
            <p className="text-gray-400 text-sm leading-relaxed">
              You must be at least 13 years old to use Instagraph. By using the service, you represent
              that you meet this age requirement and have the legal capacity to enter into these Terms.
            </p>
          </Section>

          <Section title="3. Acceptable Use">
            <p className="text-gray-400 text-sm leading-relaxed">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-gray-400 text-sm mt-2">
              <li>Submit content that violates any applicable law or third-party rights</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the service at scale</li>
              <li>Use the service to process personally identifiable information of individuals without consent</li>
              <li>Submit URLs that you do not have permission to access</li>
              <li>Attempt to circumvent rate limits, authentication, or security controls</li>
              <li>Use the service in any way that damages, disables, or impairs our infrastructure</li>
              <li>Resell or sublicense access to the service without our written permission</li>
            </ul>
          </Section>

          <Section title="4. Content You Submit">
            <p className="text-gray-400 text-sm leading-relaxed">
              You retain ownership of any text or URLs you submit to Instagraph. By submitting content,
              you grant us a limited license to process that content solely to provide the service (i.e.,
              to extract entities and generate a graph).
            </p>
            <p className="text-gray-400 text-sm leading-relaxed mt-3">
              You represent that you have the right to submit any content you provide and that doing so
              does not violate any third-party intellectual property rights, privacy rights, or applicable law.
            </p>
            <p className="text-gray-400 text-sm leading-relaxed mt-3">
              <strong className="text-gray-300">Note:</strong> Content you submit is processed by OpenAI&apos;s
              API as part of the extraction pipeline. Do not submit confidential, proprietary, or sensitive
              information. See our{' '}
              <Link href="/privacy" className="text-indigo-400 hover:text-indigo-300 transition-colors">
                Privacy Policy
              </Link>{' '}
              for details.
            </p>
          </Section>

          <Section title="5. Generated Graphs">
            <p className="text-gray-400 text-sm leading-relaxed">
              Graphs generated by Instagraph are produced by AI and may contain errors, omissions, or
              inaccuracies. They are provided for informational purposes only and should not be relied
              upon as financial, legal, or investment advice.
            </p>
            <p className="text-gray-400 text-sm leading-relaxed mt-3">
              We make no representations about the accuracy, completeness, or timeliness of generated
              graph content.
            </p>
          </Section>

          <Section title="6. Intellectual Property">
            <p className="text-gray-400 text-sm leading-relaxed">
              The Instagraph platform, including its design, software, and original content, is owned
              by us and protected by applicable intellectual property laws. You may not copy, reproduce,
              distribute, or create derivative works from the platform without our explicit written consent.
            </p>
            <p className="text-gray-400 text-sm leading-relaxed mt-3">
              Graphs you generate from your own submitted content may be used by you for personal or
              commercial purposes.
            </p>
          </Section>

          <Section title="7. Disclaimer of Warranties">
            <p className="text-gray-400 text-sm leading-relaxed uppercase text-xs tracking-wide">
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
              AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE,
              OR SECURE.
            </p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p className="text-gray-400 text-sm leading-relaxed uppercase text-xs tracking-wide">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER
              INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE
              LOSSES, ARISING OUT OF YOUR USE OF THE SERVICE.
            </p>
          </Section>

          <Section title="9. Changes to Terms">
            <p className="text-gray-400 text-sm leading-relaxed">
              We may update these Terms at any time. We will notify you of material changes by updating
              the &ldquo;Last updated&rdquo; date. Your continued use of Instagraph after changes take effect
              constitutes acceptance of the new Terms.
            </p>
          </Section>

          <Section title="10. Termination">
            <p className="text-gray-400 text-sm leading-relaxed">
              We reserve the right to suspend or terminate your access to Instagraph at any time, with
              or without notice, for violation of these Terms or for any other reason at our sole discretion.
            </p>
          </Section>

          <Section title="11. Governing Law">
            <p className="text-gray-400 text-sm leading-relaxed">
              These Terms are governed by and construed in accordance with applicable law. Any disputes
              arising from these Terms shall be resolved through binding arbitration or in a court of
              competent jurisdiction.
            </p>
          </Section>

          <Section title="12. Contact">
            <p className="text-gray-400 text-sm leading-relaxed">
              Questions about these Terms? Contact us:
            </p>
            <div className="mt-3 p-4 rounded-xl bg-gray-900 border border-gray-800 text-sm space-y-1">
              <p className="text-gray-300 font-medium">Instagraph</p>
              <p className="text-gray-500">
                Email:{' '}
                <a href="mailto:legal@instagraph.ai" className="text-indigo-400 hover:text-indigo-300 transition-colors">
                  legal@instagraph.ai
                </a>
              </p>
            </div>
          </Section>

          {/* Footer */}
          <div className="border-t border-gray-800 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
            <Link href="/" className="text-indigo-400 hover:text-indigo-300 text-sm transition-colors">
              ← Back to Instagraph
            </Link>
            <Link href="/privacy" className="text-gray-500 hover:text-gray-300 text-sm transition-colors">
              Privacy Policy →
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-4">
      <h2 className="text-lg font-semibold text-white">{title}</h2>
      <div className="space-y-3">{children}</div>
    </div>
  )
}
